tasks:
  - init: npm install && npm run contentlayer2 build
    command: gp open posts/change-me.md && bun run dev

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    addCheck: true
