import { Inter } from 'next/font/google';
import { ThemeProvider, ThemeStateHidden } from '@repo/components/theme';

import type { Metadata } from 'next';

// import '@repo/styles';
// import '@repo/ui/styles.css';
// import '@repo/shells/styles.css';
// import '@repo/viz/styles.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export function metadata(): Metadata {
  return {
    title: {
      template: '%s | Client Apps',
      default: 'Client Apps'
    },
    description: 'Generated by create turbo'
  };
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          {children}
          <ThemeStateHidden />
        </ThemeProvider>
      </body>
    </html>
  );
}
