import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import '@styles/globals.css';
import '../style/custom.css';

const inter = Inter({ subsets: ['latin'] });

export function metadata(): Metadata {
  return {
    title: {
      template: '%s | Admin',
      default: 'Admin'
    },
    description: 'Generated by create turbo'
  };
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background`}>{children}</body>
    </html>
  );
}
